# Generated by Django 5.0.2 on 2024-02-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_passwords_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwords',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
