# Generated by Django 5.0.2 on 2024-02-14 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_alter_passwords_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwords',
            name='name',
        ),
    ]
